common-ground-uf/common-ground

- App/App.tsx
- App/data/dummyData.ts
- App/package-lock.json
- App/screens/DebugScreen.tsx
- App/screens/Home.tsx
- App/screens/Login.tsx
- App/screens/RestaurantScreen.tsx
- Fix small Android bugs
- Make the app look slightly more presentable for the demo in case Dr Thomas or Dobbins look at it
- Remove inappropriate memes from the gallery
> fix small android bugs

- App/App.tsx
- App/screens/Explore.tsx
- App/screens/Login.tsx
- The app crashes when running because of a line that was taken out in Login.tsx so I added it back
- Add margin to pictures of restaurants on Explore screen
- replace Taco Bell with Los Pollos Hermanos on Restaurant screen and Restaurant List Screen
> fix app crashing

- .github/depdendabot.yml
- .github/pull_request_template.md
- .github/workflows/eslint.yml
- .github/workflows/on-merge-main.yml
- App/.eslintignore
- App/App.tsx
- App/api/yelpApi.ts
- App/components/Navbar.tsx
- App/components/RestaurantCard.tsx
- App/screens/AllContactsScreen.tsx
- App/screens/Gallery.tsx
- App/screens/Login.tsx
- App/screens/MessagesScreen.tsx
- App/screens/Notifications.tsx
- App/screens/Privacy.tsx
- App/screens/ProfileScreen.tsx
- App/screens/ResetPassword.tsx
- App/tsconfig.json
- add workflows
- dependabot
- eslint
- rebase main when it gets merged to
- remove all dependencies from main
- add eslint dev-dependencies to App directory
- fix eslint issues
- Make typescript compiler options stricter for App directory
- add PR template
> add workflows

- Server/controllers/groups.controller.ts
- Server/interfaces/preferences.interface.ts
- Server/models/preferences.models.ts
- Server/routes/groups.route.ts
- Server/services/groups.service.ts
- Server/services/users.service.ts
- Added new preferences model, contains info about groupId, userId and list of string preferences
- Added 4 new routes addPreference, removePreference, get user preferences, and get group preferences
- Group preferences return a list of strings that aggregate all of the user preferences
> Added preferences, tied to user and group

- App/screens/Account.tsx
- App/screens/Home.spec.tsx
- App/screens/Home.tsx
- App/screens/Logout.tsx
made it so u only have to change server IP in one spot
(Config.tsx)
> Add server uri

- App/App.tsx
- App/components/HeaderProfileIcon.tsx
- App/package.json
- App/screens/AllContactsScreen.tsx
- App/screens/DebugScreen.tsx
- App/screens/Explore.tsx
- App/screens/Home.tsx
- App/screens/Login.tsx
- App/screens/MessagesScreen.tsx
- App/screens/Preferences.tsx
- App/screens/RestaurantList.tsx
- App/screens/Signup.tsx
- App/screens/StrategicOrRandom.tsx
- App/screens/WaitingOnFriends.tsx
- App/screens/__snapshots__/Explore.spec.tsx.snap
- App/screens/__snapshots__/Home.spec.tsx.snap
- App/screens/__snapshots__/RestaurantList.spec.tsx.snap
- Add routes where they are missing
- add profile icon in header that links to profile page
- add artificial loading on Waiting on friends screen
- add command that starts the app in production mode and does not have the debug screeen
> Getting kicked out of waffle house at 2:45 AM

- App/.eslintrc.js
- App/App.tsx
- App/Config.tsx
- App/app.json
- App/components/HeaderProfileIcon.tsx
- App/data/dummyData.ts
- App/package-lock.json
- App/screens/DebugScreen.tsx
- App/screens/Explore.tsx
- App/screens/Login.tsx
- App/screens/MessagesScreen.tsx
- App/screens/RestaurantScreen.tsx
- App/screens/__snapshots__/RestaurantScreen.spec.tsx.snap
- Server/package-lock.json
functional messages (for now) and some fixes and changes for nav (from fix-nav)
> fix nav with somewhat functional messages with temp create group button

- Server/controllers/users.controller.ts
- Server/package-lock.json
- Server/routes/users.route.ts
- Server/services/users.service.ts
Added user preferences route
Functions the same as group prefs
- Post to /user/:id/pref add pref to set
- Delete to /user/:id/pref remove pref from set
- Get to /user/:id/pref  get prefs
- prefs are return in an array
> Added userprefs route

- App/App.tsx
- App/commonTypes.ts
- App/data/Storage.ts
- App/jest.config.js
- App/jest.setup.js
- App/package-lock.json
- App/package.json
- App/screens/Home.tsx
- App/screens/Login.tsx
- App/screens/MessagesListScreen.tsx
- App/screens/MessagesScreen.tsx
- App/screens/StartNewTableScreen.tsx
- App/screens/index.ts
- Server/controllers/groups.controller.ts
- Server/dtos/groups.dto.ts
- Server/interfaces/groups.interface.ts
- Server/models/groups.models.ts
- Server/routes/groups.route.ts
- Server/services/groups.service.ts
- getGroups by user ID route
- can use name & lastMessage parameter to get group name or last message or neither
- storage contains user info
- invitecode handled on backend for creating a new group
- added automatically add requesting user to group (backend)
- handling group name on creation
- added messages group screen
- fixed getting messages when loading group message page
- fixed self message bubbles in group (using storage)
> Messages change format

- App/screens/Home.tsx
- App/screens/MessagesListScreen.tsx
- App/screens/MessagesScreen.tsx
- App/screens/StartNewTableScreen.tsx
Fix the rest of the SERVER_URI stuff because I apparently missed some or merged it wrong lol
> New server uri to env

- .gitignore
- App/api/yelpApi.ts
- App/package-lock.json
- App/package.json
- App/screens/Account.tsx
- App/screens/Home.tsx
- App/screens/Login.tsx
- App/screens/Logout.tsx
- App/screens/MessagesListScreen.tsx
- App/screens/MessagesScreen.tsx
- App/screens/Signup.tsx
- App/screens/StartNewTableScreen.tsx
Replace dotenv with Config.tsx
> Replace dotenv with Config.tsx

- App/api/yelpHelper.ts
- App/package-lock.json
- App/package.json
- App/screens/GroupDetails.tsx
Make generate restaurant button work (untested lol)
> Implement generate restaurant

- App/package-lock.json
- App/screens/Account.tsx
- App/screens/DebugScreen.tsx
- App/screens/Settings.tsx
- App/screens/StartNewTableScreen.tsx
https://user-images.githubusercontent.com/32403644/204969694-b5eb79d0-9774-491a-ad44-a80f778f2dd6.mov
> Settings screen improvements

- App/App.tsx
- App/commonTypes.ts
- App/screens/Account.tsx
- App/screens/Home.tsx
- App/screens/Login.tsx
- App/screens/ProfileScreen.tsx
> Profile screen

- App/App.tsx
- App/screens/Home.tsx
- App/screens/JoinGroup.tsx
- App/screens/MessagesListScreen.tsx
- App/screens/MessagesScreen.tsx
- Server/controllers/groups.controller.ts
- Server/routes/groups.route.ts
- Server/services/groups.service.ts
What does your PR do?
join group by invite code
> Add join group and stuff

- App/screens/MessagesScreen.tsx
- App/screens/Preferences.tsx
What does your PR do?
edit/save preferences for users
> Preferencessss

- App/screens/Home.tsx
What does your PR do?
faixsmm home apge
> Fix home page

- App/api/yelpHelper.ts
- App/commonTypes.ts
- App/screens/Gallery.tsx
- App/screens/RestaurantScreen.tsx
Make restaurant screen correctly show pictures and remove See More button.
> Restaurant gallery

- App/App.tsx
- App/screens/GroupList.tsx
- App/screens/Home.tsx
- App/screens/MessagesListScreen.tsx
- App/screens/RestaurantScreen.tsx
> temporary fix

- App/components/RestaurantCard.tsx
- App/screens/Explore.tsx
- App/screens/Home.tsx
- App/screens/RestaurantList.tsx
> kim wexler

- App/components/GroupBubble.tsx
- App/components/__snapshots__/ContactBubble.spec.tsx.snap
- App/screens/RestaurantScreen.tsx
What does your PR do?
- fix a few sonar cloud errors
> shut the fuck up
